[package]
name = "covidd"
version = "0.1.0"
authors = ["Paul Horn <developer@knutwalker.de>"]
description = "Render current covid data for Dresden in the terminal"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/knutwalker/covidd/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
# clap = "3.0.0-beta.2"
color-eyre = { version = "0.5.6", features = ["issue-url", "tracing-error", "url"] }
# console = { version = "0.13.0", default-features = false }
crossterm = "0.18.2"
# directories = "3.0.1"
eyre = "0.6.2"
# indicatif = { version = "0.15.0" }
# itertools = "0.9.0"
# num_cpus = { version = "1.13.0" }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
tracing = "0.1.21"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.14"
ureq = { version = "1.5.1", default-features = false, features = ["charset", "json", "tls"] }
# url = "2.1.1"

[dependencies.tui]
git = "https://github.com/knutwalker/tui-rs"
branch = "chart-top-left-legent" 
version = "0.12.0"
default-features = false
features = ["crossterm"]

[dev-dependencies]
test-case = "1.0.0"
pretty_assertions = "0.6.1"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 2
rpath = false

